myMatrix = Matrix(int(input()), int(input()))
firstMatrix = myMatrix.nhapcau1()
secondMatrix = myMatrix.nhapcau2()
Matrix.cong(myMatrix,firstMatrix=firstMatrix, secondMatrix=secondMatrix)
Matrix.tru(myMatrix, firstMatrix=firstMatrix, secondMatrix=secondMatrix)
Matrix.nhan(myMatrix, firstMatrix=firstMatrix, secondMatrix=secondMatrix)
Matrix.tich(myMatrix, firstMatrix=firstMatrix, secondMatrix=secondMatrix)